exports.QUESTIONS_DATA = [
  {
    qid: 1,
    qowner: 'public',
    qkey: '1NT01',
    qtitle: '1NT ',
    qdetail: 'AKJx, AQxxx, Kx xx what is the opening bid, what is your rebid ?',
    qanswer_correct: '1H',
    qanswer_bad1: '1NT',
    qanswer_bad2: '1S',
    qanswer_bad3: null,
    qhyperlink1: null,
    qhyperlink2: null,
    qgroup1: '1NT',
    qgroup2: 'Bridge Bidding'
  },
  {
    qid: 2,
    qowner: 'public',
    qkey: '1NT02',
    qtitle: null,
    qdetail: 'AKx, AQxxx, KJx xx what is the opening bid, what is your rebid ?',
    qanswer_correct: '1NT',
    qanswer_bad1: '1H',
    qanswer_bad2: '1D',
    qanswer_bad3: null,
    qhyperlink1: null,
    qhyperlink2: null,
    qgroup1: '1NT',
    qgroup2: 'Bridge Bidding'
  },
  {
    qid: 3,
    qowner: 'public',
    qkey: '1NT03',
    qtitle: null,
    qdetail: '1NT  P  2C  P,  2D  Pass',
    qanswer_correct: 'Garbage Stayman',
    qanswer_bad1: 'Has long diamonds',
    qanswer_bad2: 'Transfer to hearts',
    qanswer_bad3: null,
    qhyperlink1: null,
    qhyperlink2: null,
    qgroup1: '1NT',
    qgroup2: 'Bridge Bidding'
  },
  {
    qid: 4,
    qowner: 'public',
    qkey: '1NT04',
    qtitle: null,
    qdetail: '1NT  P  2C  P, 2D  P  2NT',
    qanswer_correct: 'Range Finder',
    qanswer_bad1: 'Transfer to Minors',
    qanswer_bad2: 'Transfer to Diamonds',
    qanswer_bad3: null,
    qhyperlink1: null,
    qhyperlink2: null,
    qgroup1: '1NT',
    qgroup2: 'Bridge Bidding'
  },
  {
    qid: 5,
    qowner: 'public',
    qkey: '1NT05',
    qtitle: null,
    qdetail: '1NT  P  2C  P, 2D  P  3H',
    qanswer_correct: 'Smolen 5 Spades, 4 Hearts',
    qanswer_bad1: 'Transfer to Spades',
    qanswer_bad2: 'Invitational Hearts',
    qanswer_bad3: null,
    qhyperlink1: null,
    qhyperlink2: null,
    qgroup1: '1NT',
    qgroup2: 'Bridge Bidding'
  }
]
